controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    mz25_arm_controller:
      type: forward_joint_trajectory_controller/ForwardJointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

mz25_arm_controller:
  ros__parameters:
    joints:
      - mz25_joint1
      - mz25_joint2
      - mz25_joint3
      - mz25_joint4
      - mz25_joint5
      - mz25_joint6
      
    constraints:
      goal_time: 0.6
      mz25_joint1:
        goal: 0.02
      mz25_joint2:
        goal: 0.02
      mz25_joint3:
        goal: 0.02
      mz25_joint4:
        goal: 0.02
      mz25_joint5:
        goal: 0.02
      mz25_joint6:
        goal: 0.02

